"""Ports owned by the Memory bounded context."""

from typing import Protocol

from boxagent.domain.memory.models import MemoryIngestionJob


class MemoryUnavailable(RuntimeError):
    """The configured memory backend is unavailable or violated its protocol."""


class MemoryBackend(Protocol):
    async def health(self) -> dict: ...
    async def remember(self, observations: list[dict]) -> dict: ...
    async def remember_narrative(self, checkpoint: dict, *,
                                 metadata: dict | None = None) -> dict: ...
    async def query(self, question: str, *, top_k: int = 5,
                    mode: str = "deep") -> dict: ...
    async def inspect(self, *, query: str = "", selected_id: str | None = None,
                      node_limit: int = 100, edge_limit: int = 200) -> dict: ...
    async def forget(self, memory_ids: list[str]) -> dict: ...
    async def save(self) -> dict: ...
    async def close(self) -> None: ...


class MemoryJobStore(Protocol):
    async def start(self) -> None: ...
    async def enqueue_job(self, *, session_id: str, interaction_id: str,
                          source_hash: str, admission_version: str) \
            -> MemoryIngestionJob: ...
    async def jobs(self, *, statuses: set[str] | None = None) \
            -> list[MemoryIngestionJob]: ...
    async def update_job(self, job: MemoryIngestionJob) -> MemoryIngestionJob: ...


class ProfileConstructor(Protocol):
    async def propose(self, observation: str,
                      current_fields: dict) -> list[dict]: ...
