"""Persistence port owned by the Skill feature."""

from pathlib import Path
from typing import Protocol

from boxagent.domain.skill.models import SkillRecord


class SkillRepository(Protocol):
    def list(self) -> list[SkillRecord]: ...
    def create(self, skill_id: str, *, name: str, description: str,
               instructions: str) -> SkillRecord: ...
    def update(self, skill_id: str, *, name: str, description: str,
               instructions: str) -> SkillRecord: ...
    def set_enabled(self, skill_id: str, enabled: bool) -> SkillRecord: ...
    def delete(self, skill_id: str) -> None: ...
    def roots(self) -> tuple[Path, ...]: ...
