"""Persistence port owned by the Skill feature."""

from pathlib import Path
from typing import Protocol

from boxagent.domain.skill.models import SkillDraft, SkillRecord


class SkillRepository(Protocol):
    def list(self) -> list[SkillRecord]: ...
    def validate(self, skill_id: str, *, name: str, description: str,
                 instructions: str) -> None: ...
    def create(self, skill_id: str, *, name: str, description: str,
               instructions: str) -> SkillRecord: ...
    def update(self, skill_id: str, *, name: str, description: str,
               instructions: str) -> SkillRecord: ...
    def set_enabled(self, skill_id: str, enabled: bool) -> SkillRecord: ...
    def delete(self, skill_id: str) -> None: ...
    def roots(self) -> tuple[Path, ...]: ...


class SkillDraftRepository(Protocol):
    def save(self, draft: SkillDraft) -> SkillDraft: ...
    def get(self, draft_id: str) -> SkillDraft: ...
    def list(self, *, session_id: str = "",
             statuses: tuple[str, ...] = ()) -> list[SkillDraft]: ...
    def latest(self, *, session_id: str,
               statuses: tuple[str, ...]) -> SkillDraft | None: ...
